
POST http://localhost:4000/producto/create
Content-Type: application/json

{
    "idV": 0,
    "idC": 4,
    "idT": 4,
    "precio": 400
}

###
PUT http://localhost:4000/producto/updatePrecioCompra
Content-Type: application/json

{
    "idV": 0,
    "idC": 4,
    "idT": 4,
    "precio": 500
}

###
DELETE http://localhost:4000/producto/deleteByComination
Content-Type: application/json

{
    "idV": 0,
    "idC": 4,
    "idT": 4
}