POST http://localhost:4000/comprador/create
Content-Type: application/json

{
    "id": 3,
    "nombre": "Juan Mortega"
}

###
POST http://localhost:4000/tipoProducto/create
Content-Type: application/json

{
    "id": 1,
    "descripcion": "Electrodomesticos"
}

###

POST http://localhost:4000/vendedor/create
Content-Type: application/json

{
    "id": 3,
    "nombre": "Jorge Arriagada"
}




###

PUT http://localhost:4000/comprador/updateNombre/0
Content-Type: application/json

{
    "nombre": "Pedro Donoso"
}

###
PUT http://localhost:4000/vendedor/updateNombre/3
Content-Type: application/json

{
    "nombre": "Fabrian riquelme"
}

###
PUT http://localhost:4000/tipoProducto/updateDescripcion/1
Content-Type: application/json

{
    "descripcion": "Electrodomesticos2"
}

###
PUT http://localhost:4000/tipoProducto/updateID/1
Content-Type: application/json

{
    "id": 4
}

###
PUT http://localhost:4000/comprador/updateID/3
Content-Type: application/json

{
    "id": 4
}

###
PUT http://localhost:4000/vendedor/updateID/3
Content-Type: application/json

{
    "id": 2
}

###
DELETE http://localhost:4000/tipoProducto/delete/4
###

DELETE  http://localhost:4000/comprador/delete/2

###
DELETE http://localhost:4000/vendedor/delete/2