###
POST http://localhost:4000/tipoProducto/create
Content-Type: application/json

{
    "id": 1,
    "descripcion": "Electrodomesticos"
}

###
PUT http://localhost:4000/tipoProducto/updateDescripcion/1
Content-Type: application/json

{
    "descripcion": "Electrodomesticos2"
}

###
PUT http://localhost:4000/tipoProducto/updateID/1
Content-Type: application/json

{
    "id": 4
}

###
DELETE http://localhost:4000/tipoProducto/delete/4