###
POST http://localhost:4000/tipoProducto/create
Content-Type: application/json

{
    "id": 1,
    "descripcion": "Electrodomesticos"
}

###
GET http://localhost:4000/tipoProducto/getAll
Content-Type: application/json

###
GET http://localhost:4000/tipoProducto/getById/4
Content-Type: application/json

###
PUT http://localhost:4000/tipoProducto/updateDescripcion/2
Content-Type: application/json

{
    "descripcion": "Electrodomesticos7"
}

###
PUT http://localhost:4000/tipoProducto/updateID/2
Content-Type: application/json

{
    "id": 3
}

###
DELETE http://localhost:4000/tipoProducto/delete/3