###

POST http://localhost:4000/vendedor/create
Content-Type: application/json

{
    "id": 6,
    "nombre": "Jorge Arriagada"
}

###
PUT http://localhost:4000/vendedor/updateNombre/6
Content-Type: application/json

{
    "nombre": "Ricador Donoso"
}

###
PUT http://localhost:4000/vendedor/updateID/6
Content-Type: application/json

{
    "id": 3
}

###
DELETE http://localhost:4000/vendedor/delete/3
